inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - spec/fixtures/**/*
    - vendor/bundle/**/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: '3.1'

# Disabled
Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 200
