name: "mend"

on:
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  mend:
    uses: "puppetlabs/cat-github-actions/.github/workflows/mend_ruby.yml@maint-move_mend_if_condition"
    secrets: "inherit"
